function Output = Ttilde_10x1(SpatialVelocity, TransformationMat)
    Output=transpose([transpose(SpatialVelocity(1:3))/2*...
        KMatrix_3x6(SpatialVelocity(1:3)),...
        transpose(SpatialVelocity(4:6))*...
        Vector2Matrix_3x3(SpatialVelocity(4:6))*...
        TransformationMat(1:3,1:3),...
        transpose(SpatialVelocity(4:6))/2*...
        SpatialVelocity(1:3)]);
end