# Load data settings
DATA_LOADER:
  INPUT_DATA_PATH: Data/KinematicsData.mat
  OUTPUT_DATA_PATH: Data/DynRegVecData.mat
  BATCH_SIZE: 16
  SPLIT_RATIO: [ 6, 2, 2 ]
  SHUFFLE: True
  PIN_MEMORY: True

# Network settings
NETWORK:
  INPUT_SIZE: 28
  OUTPUT_SIZE: 413
  HIDDEN_SIZE: [ 128, 256, 512 ]

# Training settings
TRAIN:
  INIT: Kaiming # False, Zero, Xavier, Kaiming
  LEARNING_RATE: 0.01
  WEIGHT_DECAY: 0.0
  NUM_EPOCHS: 30
  DEVICE: 0 # -1 for CPU
  GRAD_MAX: 10.0

# Visualization settings
VISUALIZATION:
  LOSS_EPOCH_DIAGRAM:
    TITLE_FONTSIZE: 20
    LABEL_FONTSIZE: 15
    X_SEGMENT: 10
    Y_SCALE: linear # linear, log, symlog, logit
    LINE_WIDTH: 2 # default: 1.5
  NN_WEIGHT:
    NUM_ROW: -1 # -1 for default
    NUM_COL: -1 # -1 for default
    FIG_SIZE: [ -1, -1 ] # [ -1, * ] or [ *, -1 ] for default
    DPI: 100
    COLOR_MAP: seismic
    TITLE_FONTSIZE: 15
